/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Health check endpoint.
         */
        get: operations["health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Get current user profile, creating it on first call.
         */
        get: operations["me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch
         * @description Update current user profile fields.
         */
        patch: operations["me_patch"];
        trace?: never;
    };
    "/v1/notebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List
         * @description List notebooks owned by caller newest first, with demo notebook prepended on page 1.
         */
        get: operations["notebooks_list"];
        put?: never;
        /**
         * Create
         * @description Create a new notebook with default values.
         */
        post: operations["notebooks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Get a readable notebook by ID.
         */
        get: operations["notebooks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List
         * @description List sources in a notebook ordered by ref_n ascending with cursor pagination.
         */
        get: operations["sources_list"];
        put?: never;
        /**
         * Create
         * @description Upload and ingest a PDF source document for a notebook.
         */
        post: operations["sources_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/sources/{src}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Get source document details by ID.
         */
        get: operations["sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/sources/{src}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Stream PDF source file with HTTP Range support for viewer.
         */
        get: operations["sources_get_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post
         * @description Stateless source-grounded question answering over a notebook.
         */
        post: operations["ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List
         * @description List topics for a readable notebook sorted by order.
         */
        get: operations["topics_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/topics/{t}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Return citations for all locations where this topic is covered.
         */
        get: operations["topics_list_sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/question-bank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["question_bank_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["quizzes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/quizzes/{q}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["quizzes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/quizzes/{q}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["quizzes_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/quizzes/{q}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish */
        post: operations["quizzes_finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List
         * @description List chats for the caller in a readable notebook, ordered by updated_at descending.
         */
        get: operations["chats_list"];
        put?: never;
        /**
         * Create
         * @description Create a new chat in a readable notebook.
         */
        post: operations["chats_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}/chats/{c}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description List messages for a chat, newest pages first, chronological within page.
         */
        get: operations["chats_list_messages"];
        put?: never;
        /**
         * Send
         * @description Send a message to a chat, execute answering pipeline, and save turn transactionally.
         */
        post: operations["chats_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description Request payload for POST /v1/notebooks/{nb}/ask.
         */
        AskRequest: {
            /** Question */
            question: string;
            /** Topic Id */
            topic_id?: string | null;
            refs?: components["schemas"]["Refs"] | null;
            /**
             * Allow Outside
             * @default false
             */
            allow_outside: boolean;
        };
        /**
         * AskResponse
         * @description Response envelope for POST /v1/notebooks/{nb}/ask matching api-contract.md.
         */
        AskResponse: {
            /** Paragraphs */
            paragraphs: components["schemas"]["Paragraph"][];
            /** Context */
            context: components["schemas"]["ContextChunk"][];
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** Body_sources_create */
        Body_sources_create: {
            /** File */
            file: string;
            /**
             * Role
             * @default content
             * @enum {string}
             */
            role: "content" | "syllabus";
        };
        /**
         * ChatCreate
         * @description Request body for POST /v1/notebooks/{nb}/chats.
         */
        ChatCreate: {
            /** Name */
            name?: string | null;
            /** Topic Id */
            topic_id?: string | null;
        };
        /**
         * ChatList
         * @description Paginated list of chats.
         */
        ChatList: {
            /** Items */
            items: components["schemas"]["ChatOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ChatMessageCreate
         * @description Request body for POST /v1/notebooks/{nb}/chats/{c}/messages.
         */
        ChatMessageCreate: {
            /** Text */
            text: string;
            refs?: components["schemas"]["Refs"] | null;
            /**
             * Allow Outside
             * @default false
             */
            allow_outside: boolean;
        };
        /**
         * ChatOut
         * @description Response model for a chat document.
         */
        ChatOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Topic Id */
            topic_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
        };
        /**
         * ChatSendOut
         * @description Response envelope for POST /v1/notebooks/{nb}/chats/{c}/messages.
         */
        ChatSendOut: {
            user_message: components["schemas"]["MessageOut"];
            assistant_message: components["schemas"]["MessageOut"];
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /**
         * Citation
         * @description Source citation pointing to original material.
         */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            loc: components["schemas"]["Location"];
            /** Label */
            label: string;
            /** Open */
            open: components["schemas"]["OpenPdfTarget"] | components["schemas"]["OpenYouTubeTarget"];
        };
        /**
         * ContextChunk
         * @description Retrieved chunk context returned alongside the answer.
         */
        ContextChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Text */
            text: string;
            loc: components["schemas"]["Location"];
            /** Score */
            score: number;
        };
        /**
         * Counts
         * @description Aggregate counts for notebook artifacts.
         */
        Counts: {
            /**
             * Chunks
             * @default 0
             */
            chunks: number;
            /**
             * Questions Verified
             * @default 0
             */
            questions_verified: number;
        };
        /** Feedback */
        Feedback: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "correct" | "incorrect" | "partial";
            /** Correct Answer */
            correct_answer: string;
            /** Correct Option Id */
            correct_option_id?: string | null;
            /** Explanation */
            explanation: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Misconception */
            misconception?: string | null;
            /** Rubric Coverage */
            rubric_coverage?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Image
         * @description Image reference within a paragraph.
         */
        Image: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "extracted" | "diagram" | "ai_generated" | "search_link";
            /** Url */
            url: string;
            /** Caption */
            caption: string;
            citation?: components["schemas"]["Citation"] | null;
        };
        /**
         * Location
         * @description Source location matching data-model.md.
         */
        Location: {
            /** Source Id */
            source_id: string;
            /** Page */
            page?: number | null;
            /** Page Label */
            page_label?: string | null;
            /** Slide */
            slide?: number | null;
            /** Bbox */
            bbox?: number[] | null;
            /** T Start S */
            t_start_s?: number | null;
            /** T End S */
            t_end_s?: number | null;
            /** Section */
            section?: string | null;
            /** Url */
            url?: string | null;
            /** Anchor */
            anchor?: string | null;
            /** Sheet */
            sheet?: string | null;
            /** Cell Range */
            cell_range?: string | null;
        };
        /**
         * MessageList
         * @description Paginated list of messages.
         */
        MessageList: {
            /** Items */
            items: components["schemas"]["MessageOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * MessageOut
         * @description Public message model matching data-model.md.
         */
        MessageOut: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Text */
            text?: string | null;
            /** Paragraphs */
            paragraphs?: components["schemas"]["Paragraph"][] | null;
            refs?: components["schemas"]["Refs"];
            /** Context */
            context?: components["schemas"]["ContextChunk"][] | null;
        };
        /**
         * Notebook
         * @description Notebook document matching data-model.md plus id.
         */
        Notebook: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Owner Uid */
            owner_uid: string;
            /** Is Demo */
            is_demo: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "empty" | "processing" | "ready";
            /** Sources Summary */
            sources_summary?: components["schemas"]["SourceSummary"][];
            counts?: components["schemas"]["Counts"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * NotebookCreate
         * @description Payload for creating a new notebook.
         */
        NotebookCreate: {
            /** Name */
            name: string;
        };
        /**
         * NotebookList
         * @description Paginated list of notebooks.
         */
        NotebookList: {
            /** Items */
            items: components["schemas"]["Notebook"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * OpenPdfTarget
         * @description Target for opening a PDF viewer at a specific page and optional bounding box.
         */
        OpenPdfTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pdf";
            /** Source Id */
            source_id: string;
            /** Page */
            page: number;
            /** Bbox */
            bbox?: number[] | null;
        };
        /**
         * OpenYouTubeTarget
         * @description Target for opening a YouTube video at a specific URL with timestamp offset.
         */
        OpenYouTubeTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "youtube";
            /** Url */
            url: string;
        };
        /**
         * Paragraph
         * @description Generated answer paragraph with supporting citations.
         */
        Paragraph: {
            /** Id */
            id: string;
            /** Section */
            section?: string | null;
            /** Text */
            text: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Outside Course
             * @default false
             */
            outside_course: boolean;
            /** Images */
            images?: components["schemas"]["Image"][];
        };
        /** QuestionBankItem */
        QuestionBankItem: {
            /** Topic Id */
            topic_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "mcq" | "numerical" | "short";
            /** Verified */
            verified: number;
            /** Rejected */
            rejected: number;
        };
        /** QuestionBankResponse */
        QuestionBankResponse: {
            /** Items */
            items: components["schemas"]["QuestionBankItem"][];
            /** Total Verified */
            total_verified: number;
            /** Next Cursor */
            next_cursor?: null;
        };
        /** QuestionOptionOut */
        QuestionOptionOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * QuestionOut
         * @description The only question shape sent before answering.
         */
        QuestionOut: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "mcq" | "numerical" | "short";
            /** Topic Id */
            topic_id: string;
            /** Difficulty */
            difficulty: number;
            /** Stem */
            stem: string;
            /** Options */
            options?: components["schemas"]["QuestionOptionOut"][] | null;
        };
        /** QuizAnswerRecord */
        QuizAnswerRecord: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
            feedback: components["schemas"]["Feedback"];
        };
        /** QuizAnswerRequest */
        QuizAnswerRequest: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
            /** Time Ms */
            time_ms: number;
        };
        /** QuizAnswerResponse */
        QuizAnswerResponse: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
            /** Already Answered */
            already_answered: boolean;
            feedback: components["schemas"]["Feedback"];
        };
        /** QuizCreate */
        QuizCreate: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "chosen" | "adaptive" | "diagnostic";
            /** Topic Ids */
            topic_ids?: string[] | null;
            /**
             * Count
             * @default 5
             */
            count: number;
        };
        /** QuizOut */
        QuizOut: {
            /** Id */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "chosen" | "adaptive" | "diagnostic";
            /** Topic Ids */
            topic_ids: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "finished";
            /** Questions */
            questions: components["schemas"]["QuestionOut"][];
            /** Answers */
            answers: components["schemas"]["QuizAnswerRecord"][];
            summary?: components["schemas"]["QuizSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuizSummary */
        QuizSummary: {
            /** Quiz Id */
            quiz_id: string;
            /**
             * Status
             * @constant
             */
            status: "finished";
            /** Total */
            total: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Score */
            score: number;
            /** By Topic */
            by_topic: components["schemas"]["TopicSummaryItem"][];
            /** Report */
            report?: null;
        };
        /**
         * Refs
         * @description Explicit references filter for search (accepted and ignored until S5).
         */
        Refs: {
            /** Sources */
            sources?: string[];
        };
        /**
         * SourceList
         * @description Paginated list of sources.
         */
        SourceList: {
            /** Items */
            items: components["schemas"]["SourceOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * SourceOut
         * @description External view of a source matching api-contract.md.
         */
        SourceOut: {
            /** Id */
            id: string;
            /** Ref N */
            ref_n: number;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "slides_pdf" | "pptx" | "docx" | "video" | "markdown" | "html" | "xlsx" | "web";
            /**
             * Role
             * @enum {string}
             */
            role: "content" | "syllabus";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "ready" | "failed";
            /** Stage */
            stage?: string | null;
            /** Error */
            error?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Duration S */
            duration_s?: number | null;
            /** Licence */
            licence?: string | null;
            /** Attribution */
            attribution?: string | null;
            /** Youtube Url */
            youtube_url?: string | null;
        };
        /**
         * SourceSummary
         * @description Summary of a source document in a notebook.
         */
        SourceSummary: {
            /** Source Id */
            source_id: string;
            /** Ref N */
            ref_n: number;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "slides_pdf" | "pptx" | "docx" | "video" | "markdown" | "html" | "xlsx" | "web";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "ready" | "failed";
        };
        /**
         * TopicList
         * @description Topic list response shape matching api-contract.md.
         */
        TopicList: {
            /** Items */
            items: components["schemas"]["TopicListItem"][];
            /** Next Cursor */
            next_cursor?: null;
        };
        /**
         * TopicListItem
         * @description Topic list item matching api-contract.md.
         */
        TopicListItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Summary */
            summary: string;
            /**
             * Is Other
             * @default false
             */
            is_other: boolean;
            /** Prerequisite Ids */
            prerequisite_ids?: string[];
            /**
             * Location Count
             * @default 0
             */
            location_count: number;
        };
        /**
         * TopicSourceList
         * @description Topic sources response shape matching api-contract.md.
         */
        TopicSourceList: {
            /** Items */
            items: components["schemas"]["Citation"][];
            /** Next Cursor */
            next_cursor?: null;
        };
        /** TopicSummaryItem */
        TopicSummaryItem: {
            /** Topic Id */
            topic_id: string;
            /** Total */
            total: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
        };
        /**
         * User
         * @description User profile document matching data-model.md plus id.
         */
        User: {
            /** Id */
            id: string;
            /** Email */
            email?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Is Guest
             * @default false
             */
            is_guest: boolean;
            /** Study Coach */
            study_coach?: boolean | null;
            format?: components["schemas"]["UserFormat"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserFormat
         * @description User response formatting instructions.
         */
        UserFormat: {
            /** Custom Instructions */
            custom_instructions?: string | null;
        };
        /**
         * UserPatch
         * @description Payload for partial user update.
         */
        UserPatch: {
            /** Study Coach */
            study_coach?: boolean | null;
            format?: components["schemas"]["UserFormat"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notebooks_list: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notebooks_create: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notebooks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_list: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_create: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_sources_create"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
                src: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_get_file: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
                authorization?: string | null;
            };
            path: {
                nb: string;
                src: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_list: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_list_sources: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
                t: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicSourceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    question_bank_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionBankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quizzes_create: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quizzes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
                q: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quizzes_answer: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
                q: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quizzes_finish: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
                q: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chats_list: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chats_create: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chats_list_messages: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
                c: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chats_send: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
