/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Health check endpoint.
         */
        get: operations["health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Get current user profile, creating it on first call.
         */
        get: operations["me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch
         * @description Update current user profile fields.
         */
        patch: operations["me_patch"];
        trace?: never;
    };
    "/v1/notebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List
         * @description List notebooks owned by caller newest first, with demo notebook prepended on page 1.
         */
        get: operations["notebooks_list"];
        put?: never;
        /**
         * Create
         * @description Create a new notebook with default values.
         */
        post: operations["notebooks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notebooks/{nb}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Get a readable notebook by ID.
         */
        get: operations["notebooks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Counts
         * @description Aggregate counts for notebook artifacts.
         */
        Counts: {
            /**
             * Chunks
             * @default 0
             */
            chunks: number;
            /**
             * Items
             * @default 0
             */
            items: number;
            /**
             * Questions Verified
             * @default 0
             */
            questions_verified: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Notebook
         * @description Notebook document matching data-model.md plus id.
         */
        Notebook: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Owner Uid */
            owner_uid: string;
            /** Is Demo */
            is_demo: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "empty" | "processing" | "ready";
            /** Sources Summary */
            sources_summary?: components["schemas"]["SourceSummary"][];
            counts?: components["schemas"]["Counts"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * NotebookCreate
         * @description Payload for creating a new notebook.
         */
        NotebookCreate: {
            /** Name */
            name: string;
        };
        /**
         * NotebookList
         * @description Paginated list of notebooks.
         */
        NotebookList: {
            /** Items */
            items: components["schemas"]["Notebook"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * SourceSummary
         * @description Summary of a source document in a notebook.
         */
        SourceSummary: {
            /** Source Id */
            source_id: string;
            /** Ref N */
            ref_n: number;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "slides_pdf" | "pptx" | "docx" | "video" | "markdown" | "html" | "xlsx" | "web";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "ready" | "failed";
        };
        /**
         * User
         * @description User profile document matching data-model.md plus id.
         */
        User: {
            /** Id */
            id: string;
            /** Email */
            email?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Is Guest
             * @default false
             */
            is_guest: boolean;
            /** Study Coach */
            study_coach?: boolean | null;
            format?: components["schemas"]["UserFormat"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserFormat
         * @description User response formatting instructions.
         */
        UserFormat: {
            /** Custom Instructions */
            custom_instructions?: string | null;
        };
        /**
         * UserPatch
         * @description Payload for partial user update.
         */
        UserPatch: {
            /** Study Coach */
            study_coach?: boolean | null;
            format?: components["schemas"]["UserFormat"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notebooks_list: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notebooks_create: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notebooks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                nb: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
